version: '3'

services:
  postgresql-wal2json:
    image: galihsatriawan/postgres-wal2json:wal2json-0.0.1
    container_name: pg-docker-with-wal2json
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always